# Generated by Django 4.0.10 on 2024-01-22 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weatherapikey',
            old_name='api_key',
            new_name='weather_api_key',
        ),
    ]
